version: '3.7'
services:
  backend:
    build:
      context: backend/
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
  client:
    build:
      context: client/
    restart: always
    ports:
    - "8080:8080"
    env_file:
      - .env